home:
  path: /
  controller: App\Controller\HomeController::index

login:
  path: /login
  controller: App\Controller\AuthController::login

register:
  path: /register
  controller: App\Controller\AuthController::register

logout:
  path: /logout
  controller: App\Controller\AuthController::logout
