home:
  path: /
  controller: App\Controller\HomeController::index

login:
  path: /login
  controller: App\Controller\LoginController::login

register:
  path: /register
  controller: App\Controller\RegisterController::register

create_blog:
  path: /create-blog
  controller: App\Controller\CreateBlogController::index

update_blog:
  path: /update-blog
  controller: App\Controller\UpdateBlogController::updateBlogPost

delete_blog:
  path: /delete-blog
  controller: App\Controller\DeleteBlogController::deleteBlogPost

add_comment:
  path: /add-comment
  controller: App\Controller\AddCommentController::addComment

filter_by_category:
  path: /filter-by-category
  controller: App\Controller\HomeController::filterByCategories

logout:
  path: /logout
  controller: App\Controller\LogoutController::logout
